import json
import os
import re
import tempfile
from datetime import UTC, datetime

from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, String, Text, create_engine
from sqlalchemy.orm import declarative_base, sessionmaker


def _now():
    return datetime.now(UTC)


def _database_url() -> str:
    url = os.getenv("DATABASE_URL")
    if not url:
        # Temp dir works everywhere, including read-only serverless filesystems.
        return "sqlite:///" + os.path.join(tempfile.gettempdir(), "vaani.db")
    # Neon / Supabase / Render hand out postgres:// URLs; name the psycopg 3 driver.
    return re.sub(r"^postgres(ql)?://", "postgresql+psycopg://", url)


DATABASE_URL = _database_url()
_is_sqlite = DATABASE_URL.startswith("sqlite")

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if _is_sqlite else {},
    pool_pre_ping=not _is_sqlite,   # serverless Postgres drops idle connections
)
SessionLocal = sessionmaker(bind=engine)
Base = declarative_base()


class Staff(Base):
    __tablename__ = "staff"

    username = Column(String, primary_key=True)
    password_hash = Column(String, nullable=False)
    role = Column(String, nullable=False, default="staff")   # "staff" | "admin"
    created_at = Column(DateTime(timezone=True), default=_now)


class BankingSession(Base):
    __tablename__ = "sessions"

    id = Column(String, primary_key=True)          # UUID generated by the frontend
    staff_id = Column(String, ForeignKey("staff.username"), index=True, nullable=True)
    created_at = Column(DateTime(timezone=True), default=_now)
    updated_at = Column(DateTime(timezone=True), default=_now, onupdate=_now)
    customer_language = Column(String, default="hindi")
    detected_intent = Column(String, nullable=True)
    summary = Column(Text, nullable=True)           # JSON: english_summary, vernacular_summary


class ConversationTurn(Base):
    __tablename__ = "conversation_turns"

    id = Column(Integer, primary_key=True, autoincrement=True)
    session_id = Column(String, ForeignKey("sessions.id"), index=True, nullable=False)
    role = Column(String)                          # "customer" or "staff"
    original_text = Column(Text)
    translated_text = Column(Text)
    language = Column(String)
    intent = Column(String, nullable=True)
    confidence = Column(Float, nullable=True)
    entities = Column(Text, default="{}")          # JSON string
    timestamp = Column(DateTime(timezone=True), default=_now)

    def entities_dict(self):
        return json.loads(self.entities or "{}")


def init_db():
    # ponytail: create_all only adds missing tables; add Alembic when a column changes.
    Base.metadata.create_all(bind=engine)
